#### Torch Import

In [36]:
import torch
import torch.nn as nn
import torch.nn.functional as F

#### CUDA Check

In [37]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

print(device)

cuda


#### Basic Test

In [38]:
# Read the contents of the file 'infinite_in_modern_thought.txt' and store it in the variable 'text'
with open('infinite_in_modern_thought.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# Print the first 1000 characters of the text
# print(text[:1000])

# Create a list of unique characters in the text and sort them
chars = sorted(list(set(text)))
# print(chars)

# Print the number of unique characters
# print(len(chars))

# print(text[:1000])
chars = sorted(list(set(text)))
# print(chars)
# print(len(chars))

vocab_size = len(chars)

#### Simple Mapping

In [39]:
# Create a dictionary that maps each character to its index in the 'chars' list
string_to_index = {ch: i for i, ch in enumerate(chars)}

# Create a dictionary that maps each index to its corresponding character in the 'chars' list
index_to_string = {i: ch for i, ch in enumerate(chars)}

# Define the 'endcode' function that converts a string to a list of character indices
endcode = lambda s: [string_to_index[c] for c in s]

# Define the 'decode' function that converts a list of character indices to a string
decode = lambda l: ''.join([index_to_string[i] for i in l])

print(endcode("Hello, World!"))

print(decode(endcode("Hello, World!")))

[35, 61, 68, 68, 71, 11, 1, 50, 71, 74, 68, 60, 2]
Hello, World!


#### Torch Mapping

In [40]:
# Create a dictionary that maps each character to its index in the 'chars' list
string_to_index = {ch: i for i, ch in enumerate(chars)}

# Create a dictionary that maps each index to its corresponding character in the 'chars' list
index_to_string = {i: ch for i, ch in enumerate(chars)}

# Define the 'endcode' function that converts a string to a list of character indices
endcode = lambda s: [string_to_index[c] for c in s]

# Define the 'decode' function that converts a list of character indices to a string
decode = lambda l: ''.join([index_to_string[i] for i in l])

# Create a tensor from the encoded text using torch.tensor
data = torch.tensor(endcode(text), dtype=torch.long)

print(data[:100])

tensor([97, 47, 64, 61,  1, 43, 74, 71, 66, 61, 59, 76,  1, 34, 77, 76, 61, 70,
        58, 61, 74, 63,  1, 61, 29, 71, 71, 67,  1, 71, 62,  1, 42, 70,  1, 76,
        64, 61,  1, 76, 64, 61, 71, 74, 81,  1, 71, 62,  1, 76, 64, 61,  1, 65,
        70, 62, 65, 70, 65, 76, 61,  1, 65, 70,  1, 69, 71, 60, 61, 74, 70,  1,
        76, 64, 71, 77, 63, 64, 76,  0,  1,  1,  1,  1,  0, 47, 64, 65, 75,  1,
        61, 58, 71, 71, 67,  1, 65, 75,  1, 62])


#### Train Validation Split

In [41]:
# Split the data into train and validation sets
data_size = int(0.9 * len(data))  # Calculate the size of the train data

train_data = data[:data_size]  # Assign the first 90% of the data to the train_data variable
val_data = data[data_size:]  # Assign the remaining 10% of the data to the val_data variable

#### Tensor Process Flow

In [42]:
block_size = 8

x = train_data[:block_size]
y = train_data[1:block_size + 1]

for t in range(block_size):
    # Get the context by slicing the input sequence up to the current position
    context = x[:t + 1]
    
    # Get the target by selecting the next character in the input sequence
    target = y[t]
    
    # Print the context and target
    print(f"when input is {context}, the target: {target}")

when input is tensor([97]), the target: 47
when input is tensor([97, 47]), the target: 64
when input is tensor([97, 47, 64]), the target: 61
when input is tensor([97, 47, 64, 61]), the target: 1
when input is tensor([97, 47, 64, 61,  1]), the target: 43
when input is tensor([97, 47, 64, 61,  1, 43]), the target: 74
when input is tensor([97, 47, 64, 61,  1, 43, 74]), the target: 71
when input is tensor([97, 47, 64, 61,  1, 43, 74, 71]), the target: 66


#### Split Dataset

In [43]:
# Split the data into train and validation sets
data_size = int(0.9 * len(data))  # Calculate the size of the train data

train_data = data[:data_size]  # Assign the first 90% of the data to the train_data variable
val_data = data[data_size:]  # Assign the remaining 10% of the data to the val_data variable

# Define the get_batch function that returns a batch of data
def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

# Set the batch size
batch_size = 4

# Get a batch of training data
x, y = get_batch('train')

# Print the shape of x and y
print(x.shape, y.shape)

# Print the values of x and y
print(x)
print(y)

torch.Size([4, 8]) torch.Size([4, 8])
tensor([[24, 13,  0,  0,  1,  1,  1,  1],
        [ 1, 69, 61, 76, 64, 71, 60, 75],
        [70, 60,  1, 71, 62,  1, 69, 71],
        [63,  1, 71, 74,  1, 72, 74, 71]], device='cuda:0')
tensor([[13,  0,  0,  1,  1,  1,  1,  1],
        [69, 61, 76, 64, 71, 60, 75,  1],
        [60,  1, 71, 62,  1, 69, 71, 76],
        [ 1, 71, 74,  1, 72, 74, 71, 78]], device='cuda:0')


#### Bigram (Autoregressive Model)

In [44]:
class BigramLanguageModel(nn.Module):
    # Initialize the model with the vocabulary size
    def __init__(self, vocab_size):
        # Call the parent class's constructor
        super().__init__()
        # Create an embedding table to map token indices to vectors
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    # Define the forward pass
    def forward(self, idx, targets=None):
        # Get the logits (unnormalized probabilities) for the input indices
        logits = self.token_embedding_table(idx)
        # If targets are not provided, set the loss to None
        if targets is None:
            loss = None
        # If targets are provided, calculate the cross-entropy loss
        else:
            # Get the shape of the logits tensor (batch size, sequence length, vocab size)
            B, T, C = logits.shape
            # Reshape the logits tensor to (batch size * sequence length, vocab size)
            logits = logits.view(B*T, C)
            # Reshape the targets tensor to (batch size * sequence length)
            targets = targets.view(B*T)
            # Calculate the cross-entropy loss
            loss = F.cross_entropy(logits, targets)
        # Return the logits and loss
        return logits, loss

    # Define the generate method
    def generate(self, idx, max_new_tokens):
        # Generate new tokens one at a time
        for _ in range(max_new_tokens):
            # Get the logits and loss for the current input indices
            logits, loss = self.forward(idx)
            # Get the logits for the last token in the sequence
            logits = logits[:, -1, :]
            # Convert the logits to probabilities
            probs = F.softmax(logits, dim=-1)
            # Sample the next token from the probabilities
            idx_next = torch.multinomial(probs, num_samples=1)
            # Append the next token to the current sequence
            idx = torch.cat((idx, idx_next), dim=1)
        # Return the generated sequence
        return idx

# Create an instance of the BigramLanguageModel with the specified vocabulary size
model = BigramLanguageModel(vocab_size)
# Move the model to the specified device (e.g. GPU)
m = model.to(device)

# Create a context tensor with a single token (index 0)
context = torch.zeros((1, 1), dtype=torch.long, device=device)
# Generate a sequence of 100 tokens starting from the context
generated_chars = decode(m.generate(context, max_new_tokens=100)[0].tolist())
# Print the generated sequence
print(generated_chars)


UbuE.gQLSK(6,d’a%F9pNoes2[H +X.‘kOP([Ny:âcalZéqtt;7RwQ]Y?]f%J5ôl‘ARlY%KM6LVé]qf‘6:96csm27 :wT)Oz3wmæ


In [45]:
max_iter = 5000
learning_rate = 3e-4

optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iter):
    # Get a batch of training data
    x, y = get_batch('train')
    # Get the logits and loss
    logits, loss = model(x, y)
    # Backpropagate the loss
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    # Print the loss every 100 iterations
    if iter % 100 == 0:
        print(f"loss: {loss.item()}")

loss: 4.9653449058532715
loss: 5.223823547363281
loss: 5.172461032867432
loss: 5.214517593383789
loss: 5.067525386810303
loss: 5.29563570022583
loss: 5.170039653778076
loss: 4.969202995300293
loss: 4.522692680358887
loss: 4.965234756469727
loss: 4.814116954803467
loss: 5.387789249420166
loss: 4.864743709564209
loss: 4.696987152099609
loss: 4.775582313537598
loss: 4.4776716232299805
loss: 4.636866092681885
loss: 4.858633518218994
loss: 4.790683746337891
loss: 4.800593852996826
loss: 4.9609856605529785
loss: 4.563626766204834
loss: 4.451657772064209
loss: 4.556346416473389
loss: 4.485131740570068
loss: 4.627432823181152
loss: 4.526220321655273
loss: 4.364133358001709
loss: 4.580646514892578
loss: 4.521752834320068
loss: 4.125420570373535
loss: 4.513637542724609
loss: 4.395913124084473
loss: 4.244991779327393
loss: 4.228196144104004
loss: 4.177089691162109
loss: 4.288183689117432
loss: 4.109536170959473
loss: 4.178134918212891
loss: 4.080709934234619
loss: 4.023847579956055
loss: 3.991612

MSE (Mean Squared Error):
MSE is a commonly used loss function in regression problems. It measures the average squared difference between the predicted and actual values. The lower the MSE, the better the model's performance.

GD (Gradient Descent):
GD is an optimization algorithm used to minimize the loss function of a model. It iteratively updates the model's parameters in the direction of steepest descent of the loss function. GD can be slow for large datasets as it requires computing the gradients for the entire dataset in each iteration.

Momentum:
Momentum is an extension of GD that helps accelerate convergence and overcome local minima. It introduces a momentum term that accumulates the gradients of previous iterations and uses it to update the model's parameters. This helps the model to continue moving in the right direction even when the gradients are small.

RMSprop (Root Mean Square Propagation):
RMSprop is an optimization algorithm that adapts the learning rate for each parameter based on the average of recent squared gradients. It helps to speed up convergence by reducing the learning rate for parameters with large gradients and increasing it for parameters with small gradients.

Adam:
Adam (Adaptive Moment Estimation) is an optimization algorithm that combines the benefits of both momentum and RMSprop. It maintains a running average of both the gradients and the squared gradients, and uses them to update the model's parameters. Adam is known for its fast convergence and good performance on a wide range of problems.

AdamW:
AdamW is a variant of the Adam optimizer that incorporates weight decay regularization. Weight decay helps prevent overfitting by adding a penalty term to the loss function that discourages large parameter values. AdamW is particularly effective when dealing with models with large numbers of parameters.

These optimization algorithms are commonly used in machine learning and deep learning to train models and find the optimal set of parameters. The choice of optimizer depends on the specific problem and the characteristics of the dataset. Experimentation and tuning are often required to find the best optimizer for a given task.

#### Optimization Algorithms and Loss Functions

**MSE (Mean Squared Error):** MSE is a commonly used loss function in regression problems. It measures the average squared difference between the predicted and actual values. The lower the MSE, the better the model's performance.

**GD (Gradient Descent):** GD is an optimization algorithm used to minimize the loss function of a model. It iteratively updates the model's parameters in the direction of steepest descent of the loss function. GD can be slow for large datasets as it requires computing the gradients for the entire dataset in each iteration.

**Momentum:** Momentum is an extension of GD that helps accelerate convergence and overcome local minima. It introduces a momentum term that accumulates the gradients of previous iterations and uses it to update the model's parameters. This helps the model to continue moving in the right direction even when the gradients are small.

**RMSprop (Root Mean Square Propagation):** RMSprop is an optimization algorithm that adapts the learning rate for each parameter based on the average of recent squared gradients. It helps to speed up convergence by reducing the learning rate for parameters with large gradients and increasing it for parameters with small gradients.

**Adam:** Adam (Adaptive Moment Estimation) is an optimization algorithm that combines the benefits of both momentum and RMSprop. It maintains a running average of both the gradients and the squared gradients, and uses them to update the model's parameters. Adam is known for its fast convergence and good performance on a wide range of problems.

**AdamW:** AdamW is a variant of the Adam optimizer that incorporates weight decay regularization. Weight decay helps prevent overfitting by adding a penalty term to the loss function that discourages large parameter values. AdamW is particularly effective when dealing with models with large numbers of parameters.

These optimization algorithms are commonly used in machine learning and deep learning to train models and find the optimal set of parameters. The choice of optimizer depends on the specific problem and the characteristics of the dataset. Experimentation and tuning are often required to find the best optimizer for a given task.

In [46]:
# Create a context tensor with a single token (index 0)
context = torch.zeros((1, 1), dtype=torch.long, device=device)
# Generate a sequence of 100 tokens starting from the context
generated_chars = decode(m.generate(context, max_new_tokens=100)[0].tolist())
# Print the generated sequence
print(generated_chars)


FoP‘é…pb1ocEOLboI™XffX8éJU™4Z9cmovY/,wV$%r2y(LRKR’rst0FioE…M’,py Ofzbd4r$m)fzOA‘mMb16g Um5’lkFHU8[v0


#### Block Size and Batch Size

In [47]:
"""
NOTE:
- The block size determines the size of each block in the tensor.
- The batch size determines the number of blocks to be processed in parallel.
"""

'\nNOTE:\n- The block size determines the size of each block in the tensor.\n- The batch size determines the number of blocks to be processed in parallel.\n'