#### Torch Import

In [2]:
import time
import torch
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


#### Test Elapsed Time 

In [17]:
%%time
start_time = time.time()  # Start measuring the execution time

# Matrix multiplication
zeros = torch.zeros(3, 4)  # Create a tensor of zeros

end_time = time.time()  # Stop measuring the execution time

elapsed_time = end_time - start_time  # Calculate the elapsed time
print(f"{elapsed_time: 10f}")  # Print the elapsed time

  0.000000
CPU times: total: 0 ns
Wall time: 0 ns


In [12]:
"""
Time the execution of a matrix multiplication over GPU and CPU
"""

torch_rand_first = torch.rand(10000, 10000).to(device)
torch_rand_second = torch.rand(10000, 10000).to(device)

np_rand_first = np.random.rand(10000, 10000)
np_rand_second = np.random.rand(10000, 10000)

start_time = time.time()  # Start measuring the execution time

torch_rand_first @ torch_rand_second  # Matrix multiplication
end_time = time.time()  # Stop measuring the execution time

elapsed_time = end_time - start_time  # Calculate the elapsed time
print(f"(CUDA) GPU: {elapsed_time: 10f}")  # Print the elapsed time

start_time = time.time()  # Start measuring the execution time

np_rand_first @ np_rand_second  # Matrix multiplication
end_time = time.time()  # Stop measuring the execution time

elapsed_time = end_time - start_time  # Calculate the elapsed time
print(f"CPU: {elapsed_time: 10f}")  # Print the elapsed time

(CUDA) GPU:   0.031118
CPU:  24.276107


#### Torch Functions

In [20]:
"""
Perform multinomial sampling on the tensor with probabilities 
and print the tensor
"""

# Create a tensor with probabilities
probabilities = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5])

# Perform multinomial sampling
sampled_indices = torch.multinomial(probabilities, num_samples=3, replacement=True)

# Print the tensor
print(sampled_indices)

tensor([4, 4, 0])


In [21]:
# Create a tensor
tensor = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5])

# Concatenate the tensor with another tensor containing the value 5
out = torch.cat((tensor, torch.tensor([5])), dim=0)

# Print the concatenated tensor
print(out)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 5.0000])


In [23]:
# Create a lower triangular matrix
out = torch.tril(torch.ones(5, 5)) 
print(out)

# Create an upper triangular matrix
out = torch.triu(torch.ones(5, 5))  
print(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [25]:
# Create a tensor filled with zeros
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))

# Print the tensor
print(out)

# Calculate the exponential of the tensor
torch.exp(out)

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [32]:
input = torch.zeros(3, 4, 5)

print(input)

out = torch.transpose(input, 0, 1)

print(out.shape)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
torch.Size([4, 3, 5])


In [35]:
tensor_one = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5])
tensor_two = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5])
tensor_three = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5])

stacked = torch.stack((tensor_one, tensor_two, tensor_three))

print(stacked)

tensor([[0.1000, 0.2000, 0.3000, 0.4000, 0.5000],
        [0.1000, 0.2000, 0.3000, 0.4000, 0.5000],
        [0.1000, 0.2000, 0.3000, 0.4000, 0.5000]])


#### Important Functions

In [40]:
import torch.nn as nn

# Define the sample tensor
sample = torch.tensor([1.5, 2.5, 3.5, 4.5, 5.5])

# Define the linear layer with input size 5 and output size 3
linear = nn.Linear(5, 3, bias=False)

# Pass the sample tensor through the linear layer
out = linear(sample)

# Print the output tensor
print(out)

tensor([-3.4337, -0.6376,  1.8161], grad_fn=<SqueezeBackward4>)


In [41]:
import torch.nn.functional as F

# Define the sample tensor
sample = torch.tensor([1.5, 2.5, 3.5, 4.5, 5.5])

# Apply softmax function to the sample tensor along dimension 0
softmax = F.softmax(sample, dim=0)

# Print the softmax tensor
print(softmax)

tensor([0.0117, 0.0317, 0.0861, 0.2341, 0.6364])


In [43]:
# Define the vocabulary size and embedding dimension
vocab_size = 1000
embedding_dim = 128

# Create an embedding layer
embedding = nn.Embedding(vocab_size, embedding_dim)

# Pass a tensor of indices through the embedding layer
out = embedding(torch.tensor([1, 2, 3, 4]))

# Print the output tensor
print(out)

tensor([[ 1.0172e-01, -1.9097e+00,  1.9631e+00,  7.5606e-01, -1.1897e+00,
          2.0414e+00,  1.1170e+00,  2.5182e+00,  9.7049e-01,  2.7721e+00,
          8.8650e-01,  4.2027e-01, -7.2736e-01, -9.9180e-01,  3.1312e-01,
         -1.6686e-01,  2.0143e-01, -1.4672e+00, -4.4485e-01,  3.5430e-01,
          2.1918e-02, -1.0510e+00, -4.1342e-01, -7.0834e-01,  2.9492e+00,
         -1.8056e-02,  9.2831e-01,  9.7471e-02, -1.0939e+00, -7.5398e-02,
          6.0854e-01,  1.4911e+00,  6.6362e-01, -6.2228e-01, -7.7580e-01,
         -5.9400e-01,  8.4913e-01,  1.0868e+00, -1.9647e+00, -1.4774e+00,
          8.7803e-01, -6.3203e-01, -3.9728e-01,  6.1473e-02, -2.5838e-01,
          4.8283e-01, -5.4130e-01,  3.9844e-01,  2.0804e-01, -8.4231e-01,
          8.5253e-01,  6.7746e-01, -9.5053e-01,  6.7662e-01, -5.0145e-01,
         -1.1749e+00,  3.4841e-01,  1.7689e-01, -8.4588e-01, -7.7313e-02,
          1.7446e-01,  1.6797e+00, -5.1352e-01, -6.9137e-01, -5.5070e-01,
          1.5161e+00, -1.3931e-01, -2.

In [47]:
# Define the matrices
matrix_one = torch.tensor([[0.1, 0.2], [0.4, 0.5], [0.4, 0.5]])
matrix_two = torch.tensor([[0.4, 0.5, 0.1], [0.3, 0.4, 0.5]])

# Perform matrix multiplication
out = torch.matmul(matrix_one, matrix_two)

# Print the result
print(out)

tensor([[0.1000, 0.1300, 0.1100],
        [0.3100, 0.4000, 0.2900],
        [0.3100, 0.4000, 0.2900]])


In [52]:
""""
NOTE: 
- In PyTorch, the dtype argument is used to specify the data type of the tensor.
- In PyTorch the float dtype can not be multiplied with the int dtype
"""

int_64 = torch.randint(4, (2, 3), dtype=torch.int64)

print(int_64)

int_32 = torch.randint(4, (2, 3), dtype=torch.int32)

print(int_32)

out = int_64 * int_32

print(out)

tensor([[2, 2, 3],
        [2, 1, 3]])
tensor([[1, 0, 1],
        [3, 3, 1]], dtype=torch.int32)
tensor([[2, 0, 3],
        [6, 3, 3]])
