#### Torch Import

In [2]:
import time
import torch
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


#### Test Elapsed Time 

In [17]:
%%time
start_time = time.time()  # Start measuring the execution time

# Matrix multiplication
zeros = torch.zeros(3, 4)  # Create a tensor of zeros

end_time = time.time()  # Stop measuring the execution time

elapsed_time = end_time - start_time  # Calculate the elapsed time
print(f"{elapsed_time: 10f}")  # Print the elapsed time

  0.000000
CPU times: total: 0 ns
Wall time: 0 ns


In [12]:
"""
Time the execution of a matrix multiplication over GPU and CPU
"""

torch_rand_first = torch.rand(10000, 10000).to(device)
torch_rand_second = torch.rand(10000, 10000).to(device)

np_rand_first = np.random.rand(10000, 10000)
np_rand_second = np.random.rand(10000, 10000)

start_time = time.time()  # Start measuring the execution time

torch_rand_first @ torch_rand_second  # Matrix multiplication
end_time = time.time()  # Stop measuring the execution time

elapsed_time = end_time - start_time  # Calculate the elapsed time
print(f"(CUDA) GPU: {elapsed_time: 10f}")  # Print the elapsed time

start_time = time.time()  # Start measuring the execution time

np_rand_first @ np_rand_second  # Matrix multiplication
end_time = time.time()  # Stop measuring the execution time

elapsed_time = end_time - start_time  # Calculate the elapsed time
print(f"CPU: {elapsed_time: 10f}")  # Print the elapsed time

(CUDA) GPU:   0.031118
CPU:  24.276107


#### Torch Functions

In [20]:
"""
Perform multinomial sampling on the tensor with probabilities 
and print the tensor
"""

# Create a tensor with probabilities
probabilities = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5])

# Perform multinomial sampling
sampled_indices = torch.multinomial(probabilities, num_samples=3, replacement=True)

# Print the tensor
print(sampled_indices)

tensor([4, 4, 0])


In [21]:
# Create a tensor
tensor = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5])

# Concatenate the tensor with another tensor containing the value 5
out = torch.cat((tensor, torch.tensor([5])), dim=0)

# Print the concatenated tensor
print(out)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 5.0000])


In [23]:
# Create a lower triangular matrix
out = torch.tril(torch.ones(5, 5)) 
print(out)

# Create an upper triangular matrix
out = torch.triu(torch.ones(5, 5))  
print(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [25]:
# Create a tensor filled with zeros
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))

# Print the tensor
print(out)

# Calculate the exponential of the tensor
torch.exp(out)

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [32]:
input = torch.zeros(3, 4, 5)

print(input)

out = torch.transpose(input, 0, 1)

print(out.shape)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
torch.Size([4, 3, 5])


In [35]:
tensor_one = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5])
tensor_two = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5])
tensor_three = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5])

stacked = torch.stack((tensor_one, tensor_two, tensor_three))

print(stacked)

tensor([[0.1000, 0.2000, 0.3000, 0.4000, 0.5000],
        [0.1000, 0.2000, 0.3000, 0.4000, 0.5000],
        [0.1000, 0.2000, 0.3000, 0.4000, 0.5000]])
