#### Torch Import

In [22]:
import torch
import torch.nn as nn

#### Test Codes

In [3]:
# Generate random integers using torch
randint = torch.randint(-200, 250, (7,))

# Print the randomly generated integers
print(randint)

tensor([ 246,  106, -148,  184,  184,  190,  224])


In [4]:
# Create a tensor with the given values
tensor = torch.tensor([[0.1, 2.4], [5.7, 8], [9, 0.1]])

# Print the tensor
print(tensor)

tensor([[0.1000, 2.4000],
        [5.7000, 8.0000],
        [9.0000, 0.1000]])


In [5]:
# Create a tensor of zeros with shape (3, 4)
zeros = torch.zeros(3, 4)
print(zeros)

# Create a tensor of ones with shape (3, 4)
ones = torch.ones(3, 4)
print(ones)

# Create an empty tensor with shape (3, 4)
empty = torch.empty(3, 4)
print(empty)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6.5508e+01, 1.2331e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [6]:
# Create a tensor with values arranged from 0 to 9
arranged = torch.arange(0, 10)

# Print the tensor
print(arranged)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [7]:
# Generate a tensor with values evenly spaced between 0 and 1
linespace = torch.linspace(0, 1, steps=10)

# Print the tensor
print(linespace)

# Generate a tensor with values logarithmically spaced between 0 and 1
logspace = torch.logspace(-10, 1, steps=10)

# Print the tensor
print(logspace)

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])
tensor([1.0000e-10, 1.6681e-09, 2.7826e-08, 4.6416e-07, 7.7426e-06, 1.2915e-04,
        2.1544e-03, 3.5938e-02, 5.9948e-01, 1.0000e+01])


In [8]:
# Create an identity matrix with shape (3, 3)
eye = torch.eye(3, 3)

# Print the identity matrix
print(eye)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [9]:
value = torch.empty((2, 3), dtype=torch.int64)
print(value)

# Create a new tensor with the same shape as 'value' but uninitialized
empty_like = torch.empty_like(value)
print(empty_like)

tensor([[3780687104304,             0,             0],
        [            0,             0,             0]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [20]:
value = torch.rand((4, 2, 3))

B, T, C = value.shape

value = value.view(B * T, C)

print(value.shape)

print(value)

print(value[:, -1])

torch.Size([8, 3])
tensor([[0.7531, 0.1634, 0.3434],
        [0.3816, 0.2208, 0.6429],
        [0.1060, 0.7538, 0.8523],
        [0.8971, 0.0865, 0.9021],
        [0.5488, 0.1183, 0.8590],
        [0.4822, 0.9216, 0.2674],
        [0.9709, 0.4666, 0.5373],
        [0.2969, 0.0801, 0.8365]])
tensor([0.3434, 0.6429, 0.8523, 0.9021, 0.8590, 0.2674, 0.5373, 0.8365])


In [25]:
x = torch.tensor([-0.10], dtype=torch.float32)

y = nn.ReLU()(x)

z = nn.Sigmoid()(x)

print(x)
print(y)
print(z)

tensor([-0.1000])
tensor([0.])
tensor([0.4750])
