#### Torch Import

In [1]:
import torch

#### Test Codes

In [4]:
# Generate random integers using torch
randint = torch.randint(-200, 250, (7,))

# Print the randomly generated integers
print(randint)

tensor([  66,   80,  119, -200,   69,  118,  146])


In [8]:
# Create a tensor with the given values
tensor = torch.tensor([[0.1, 2.4], [5.7, 8], [9, 0.1]])

# Print the tensor
print(tensor)

tensor([[0.1000, 2.4000],
        [5.7000, 8.0000],
        [9.0000, 0.1000]])


In [11]:
# Create a tensor of zeros with shape (3, 4)
zeros = torch.zeros(3, 4)
print(zeros)

# Create a tensor of ones with shape (3, 4)
ones = torch.ones(3, 4)
print(ones)

# Create an empty tensor with shape (3, 4)
empty = torch.empty(3, 4)
print(empty)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6.4458e+09, 1.0608e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [12]:
# Create a tensor with values arranged from 0 to 9
arranged = torch.arange(0, 10)

# Print the tensor
print(arranged)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [13]:
# Generate a tensor with values evenly spaced between 0 and 1
linespace = torch.linspace(0, 1, steps=10)

# Print the tensor
print(linespace)

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])
